"""Teléfono del comprador opcional

Revision ID: 18c6a3e6f8d6
Revises: a3c1e2f4b5d6
Create Date: 2026-09-16 20:58:59.818944
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '18c6a3e6f8d6'
down_revision: str | None = 'a3c1e2f4b5d6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'buyer_phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'buyer_phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
