"""initial

Revision ID: fb8cf92ccd64
Revises: 
Create Date: 2026-09-16 15:44:22.204108
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'fb8cf92ccd64'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    raffle = op.create_table('raffle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ticket_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_raffle_single_row')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raffle'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'seller', name='user_role', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(length=120), nullable=False),
    sa.Column('buyer_phone', sa.String(length=30), nullable=False),
    sa.Column('is_paid', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('number BETWEEN 0 AND 99', name=op.f('ck_sales_number_range')),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('fk_sales_seller_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales')),
    sa.UniqueConstraint('number', name=op.f('uq_sales_number'))
    )
    op.create_index(op.f('ix_sales_seller_id'), 'sales', ['seller_id'], unique=False)
    op.create_index('ix_sales_created_at', 'sales', ['created_at'], unique=False)
    # ### end Alembic commands ###

    # Única fila de configuración; el admin la edita desde /admin/rifa
    op.bulk_insert(raffle, [{'id': 1, 'name': 'Rifa', 'ticket_price': 0}])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_created_at', table_name='sales')
    op.drop_index(op.f('ix_sales_seller_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_table('users')
    op.drop_table('raffle')
    # ### end Alembic commands ###
